// <auto-generated />
using System;
using LukieannLoanWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LukieannLoanWeb.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240502082443_AddDefaultLoanTypes")]
    partial class AddDefaultLoanTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LukieannLoanWeb.Data.LoanRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LoanStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("LoanTermID")
                        .HasColumnType("int");

                    b.Property<int?>("LoanTypeId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LoanStatusId");

                    b.HasIndex("LoanTermID");

                    b.HasIndex("LoanTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("LoanRequests");
                });

            modelBuilder.Entity("LukieannLoanWeb.Data.LoanStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoanStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Approved"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Cancelled"
                        });
                });

            modelBuilder.Entity("LukieannLoanWeb.Data.LoanTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Term")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("LoanTerms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Term = 3m
                        },
                        new
                        {
                            Id = 2,
                            Term = 6m
                        },
                        new
                        {
                            Id = 3,
                            Term = 12m
                        },
                        new
                        {
                            Id = 4,
                            Term = 18m
                        },
                        new
                        {
                            Id = 5,
                            Term = 12m
                        },
                        new
                        {
                            Id = 6,
                            Term = 30m
                        },
                        new
                        {
                            Id = 7,
                            Term = 36m
                        },
                        new
                        {
                            Id = 8,
                            Term = 48m
                        },
                        new
                        {
                            Id = 9,
                            Term = 60m
                        });
                });

            modelBuilder.Entity("LukieannLoanWeb.Data.LoanType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Interest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoanTypes");
                });

            modelBuilder.Entity("LukieannLoanWeb.Data.Parish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Parishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Clarendon"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hanover"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kingston"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Manchester"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Portland"
                        },
                        new
                        {
                            Id = 6,
                            Name = "St Andrew"
                        },
                        new
                        {
                            Id = 7,
                            Name = "St Ann"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Saint Catherine"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Saint Elizabeth"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Saint James"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Saint Mary"
                        },
                        new
                        {
                            Id = 12,
                            Name = "St Thomas"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Trelawny"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Westmoreland"
                        });
                });

            modelBuilder.Entity("LukieannLoanWeb.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateJoined")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("ParishId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("ParishId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "be210b42-8689-4b84-833a-97dff99352c5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e74233a2-cffd-4af6-9c4d-6cfd54d93dc3",
                            Email = "admin@test.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@TEST.COM",
                            NormalizedUserName = "ADMIN@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECqtVQ+aLhMErepmCmwYos5zu3COm2NjZc22hlpcD6ro+oDe0m3u+0QbZQ1ZPUfs8Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "188f4d4c-7182-490e-874f-8baf6b1c7757",
                            TwoFactorEnabled = false,
                            UserName = "admin@test.com"
                        },
                        new
                        {
                            Id = "cf310b42-6529-8b84-831a-97dff74352c5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2b854b7d-dc1f-4a57-9701-6dd6e2d4756e",
                            Email = "user@test.com",
                            EmailConfirmed = true,
                            FirstName = "Simple",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@TEST.COM",
                            NormalizedUserName = "USER@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEP/IfGFwLshtJvLMXyCNZEOagOn/9mtNbQSFZ8xqxnybuBCSd334DzkB17Wd8GwcLg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "92434598-ed2b-4297-8fe6-34ed891377c7",
                            TwoFactorEnabled = false,
                            UserName = "user@test.com"
                        },
                        new
                        {
                            Id = "cc511b42-6729-8b84-831a-97dff74352c4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "31d6684b-0a22-47a2-b82b-0db03b749ed4",
                            Email = "loanManager@test.com",
                            EmailConfirmed = true,
                            FirstName = "Loan",
                            LastName = "Manager",
                            LockoutEnabled = false,
                            NormalizedEmail = "LOANMANAGER@TEST.COM",
                            NormalizedUserName = "LOANMANAGER@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELTOQVhGSbExm8nQ3sGJAkHjC5slpCq8lm0a5s0FqF0x1QV48bylyf8MWxPaWnj7sQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a88121d8-7389-4318-9a26-e797e7b68c9b",
                            TwoFactorEnabled = false,
                            UserName = "loanManager@test.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "bf210b42 - 6889 - 4b74 - 833a - 97dff66352c5",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "dr210b42 - 8523 - 4b74 - 783a - 97dff66342c5",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "dr226c42 - 8723 - 4a74 - 763a - 97dff65342b4",
                            Name = "Loan Manager",
                            NormalizedName = "LOAN MANAGER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "be210b42-8689-4b84-833a-97dff99352c5",
                            RoleId = "bf210b42 - 6889 - 4b74 - 833a - 97dff66352c5"
                        },
                        new
                        {
                            UserId = "cf310b42-6529-8b84-831a-97dff74352c5",
                            RoleId = "dr210b42 - 8523 - 4b74 - 783a - 97dff66342c5"
                        },
                        new
                        {
                            UserId = "cc511b42-6729-8b84-831a-97dff74352c4",
                            RoleId = "dr226c42 - 8723 - 4a74 - 763a - 97dff65342b4"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LukieannLoanWeb.Data.LoanRequest", b =>
                {
                    b.HasOne("LukieannLoanWeb.Data.LoanStatus", "LoanStatus")
                        .WithMany()
                        .HasForeignKey("LoanStatusId");

                    b.HasOne("LukieannLoanWeb.Data.LoanTerm", "LoanTerm")
                        .WithMany()
                        .HasForeignKey("LoanTermID");

                    b.HasOne("LukieannLoanWeb.Data.LoanType", "LoanType")
                        .WithMany()
                        .HasForeignKey("LoanTypeId");

                    b.HasOne("LukieannLoanWeb.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("LoanStatus");

                    b.Navigation("LoanTerm");

                    b.Navigation("LoanType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LukieannLoanWeb.Data.User", b =>
                {
                    b.HasOne("LukieannLoanWeb.Data.Parish", "Parish")
                        .WithMany()
                        .HasForeignKey("ParishId");

                    b.Navigation("Parish");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LukieannLoanWeb.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LukieannLoanWeb.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LukieannLoanWeb.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LukieannLoanWeb.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
